---
language: node_js
node_js:
  - node
  - lts/*
cache:
  directories:
    - ~/.npm
    - .jest
jobs:
  include:
    - stage: test
      script:
        - yarn test --ci
    - stage: deploy
      if: branch = master AND (NOT type = pull_request)
      node_js: lts/*
      script:
        - yarn semantic-release
        - echo 'fs.inotify.max_user_watches=524288' | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
        - expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
        - expo publish --non-interactive
